/** Shared typography, spacing, and touch-target tokens for browse UI. */
export const zendeTokens = {
  colorVoid: "#05060A",
  colorMidnight: "#09111F",
  colorSignal: "#38D9FF",
  colorEmber: "#FF6B4A",
  colorFrost: "#F7FAFF",
  colorMist: "#9AA8B8",
  textDisplay:
    "text-[clamp(2rem,4.5vw,4rem)] font-semibold leading-[0.95] tracking-[-0.065em]",
  textPageTitle:
    "text-[clamp(1.75rem,3vw,3.25rem)] font-semibold leading-[0.98] tracking-[-0.055em]",
  textSectionTitle: "text-[20px] font-semibold leading-tight tracking-[-0.03em]",
  textShelfTitle: "text-[19px] font-semibold tracking-[-0.025em]",
  textCardTitle: "text-[17px] font-semibold tracking-[-0.02em]",
  textBody: "text-[15px] leading-relaxed",
  textMeta: "text-[13px] leading-snug",
  textBadge: "text-[11px] font-semibold uppercase tracking-[0.18em]",
  glassPanelRadius: "rounded-[32px]",
  glassCardRadius: "rounded-[24px]",
  glassCompactRadius: "rounded-[20px]",
  glassPillRadius: "rounded-full",
  touchMin: "min-h-11 min-w-11",
  safeTop: "pt-[max(0.75rem,env(safe-area-inset-top))]",
  safeBottom: "pb-[max(0.75rem,env(safe-area-inset-bottom))]",
  shelfGap: "gap-3",
  controlGap: "gap-3",
  pageX: "px-4 sm:px-6 lg:px-10 xl:px-14",
  pageMax: "mx-auto max-w-[1760px]",
} as const;
